// <auto-generated />
using System;
using CastleTours.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CastleTours.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CastleFacility", b =>
                {
                    b.Property<int>("CastlesId")
                        .HasColumnType("int");

                    b.Property<int>("FacilitiesId")
                        .HasColumnType("int");

                    b.HasKey("CastlesId", "FacilitiesId");

                    b.HasIndex("FacilitiesId");

                    b.ToTable("CastleFacility");

                    b.HasData(
                        new
                        {
                            CastlesId = 1,
                            FacilitiesId = 1
                        },
                        new
                        {
                            CastlesId = 1,
                            FacilitiesId = 2
                        },
                        new
                        {
                            CastlesId = 1,
                            FacilitiesId = 3
                        },
                        new
                        {
                            CastlesId = 2,
                            FacilitiesId = 4
                        },
                        new
                        {
                            CastlesId = 2,
                            FacilitiesId = 5
                        },
                        new
                        {
                            CastlesId = 2,
                            FacilitiesId = 1
                        },
                        new
                        {
                            CastlesId = 3,
                            FacilitiesId = 2
                        },
                        new
                        {
                            CastlesId = 3,
                            FacilitiesId = 3
                        },
                        new
                        {
                            CastlesId = 4,
                            FacilitiesId = 4
                        },
                        new
                        {
                            CastlesId = 4,
                            FacilitiesId = 5
                        },
                        new
                        {
                            CastlesId = 4,
                            FacilitiesId = 1
                        },
                        new
                        {
                            CastlesId = 4,
                            FacilitiesId = 2
                        },
                        new
                        {
                            CastlesId = 5,
                            FacilitiesId = 3
                        },
                        new
                        {
                            CastlesId = 5,
                            FacilitiesId = 4
                        });
                });

            modelBuilder.Entity("CastleTours.Shared.Models.Addon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TourId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.ToTable("Addons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum facilisis leo vel fringilla est ullamcorper. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Vitae ultricies leo integer malesuada. Dui id ornare arcu odio. Sit amet purus gravida quis blandit turpis. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing elit. Arcu dictum varius duis at. Et malesuada fames ac turpis egestas maecenas. Mi bibendum neque egestas congue quisque egestas. Sagittis orci a scelerisque purus semper. Leo vel orci porta non pulvinar neque. Tortor pretium viverra suspendisse potenti nullam ac.",
                            Name = "Lorem ipsum dolor",
                            Price = 2.00m,
                            ShortDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            TourId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum facilisis leo vel fringilla est ullamcorper. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Vitae ultricies leo integer malesuada. Dui id ornare arcu odio. Sit amet purus gravida quis blandit turpis. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing elit. Arcu dictum varius duis at. Et malesuada fames ac turpis egestas maecenas. Mi bibendum neque egestas congue quisque egestas. Sagittis orci a scelerisque purus semper. Leo vel orci porta non pulvinar neque. Tortor pretium viverra suspendisse potenti nullam ac.",
                            Name = "Lorem ipsum dolor",
                            Price = 2.00m,
                            ShortDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            TourId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum facilisis leo vel fringilla est ullamcorper. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Vitae ultricies leo integer malesuada. Dui id ornare arcu odio. Sit amet purus gravida quis blandit turpis. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing elit. Arcu dictum varius duis at. Et malesuada fames ac turpis egestas maecenas. Mi bibendum neque egestas congue quisque egestas. Sagittis orci a scelerisque purus semper. Leo vel orci porta non pulvinar neque. Tortor pretium viverra suspendisse potenti nullam ac.",
                            Name = "Lorem ipsum dolor",
                            Price = 4.00m,
                            ShortDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            TourId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum facilisis leo vel fringilla est ullamcorper. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Vitae ultricies leo integer malesuada. Dui id ornare arcu odio. Sit amet purus gravida quis blandit turpis. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing elit. Arcu dictum varius duis at. Et malesuada fames ac turpis egestas maecenas. Mi bibendum neque egestas congue quisque egestas. Sagittis orci a scelerisque purus semper. Leo vel orci porta non pulvinar neque. Tortor pretium viverra suspendisse potenti nullam ac.",
                            Name = "Lorem ipsum dolor",
                            Price = 2.50m,
                            ShortDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            TourId = 3
                        },
                        new
                        {
                            Id = 5,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum facilisis leo vel fringilla est ullamcorper. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Vitae ultricies leo integer malesuada. Dui id ornare arcu odio. Sit amet purus gravida quis blandit turpis. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing elit. Arcu dictum varius duis at. Et malesuada fames ac turpis egestas maecenas. Mi bibendum neque egestas congue quisque egestas. Sagittis orci a scelerisque purus semper. Leo vel orci porta non pulvinar neque. Tortor pretium viverra suspendisse potenti nullam ac.",
                            Name = "Lorem ipsum dolor",
                            Price = 12.00m,
                            ShortDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            TourId = 4
                        },
                        new
                        {
                            Id = 6,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum facilisis leo vel fringilla est ullamcorper. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Vitae ultricies leo integer malesuada. Dui id ornare arcu odio. Sit amet purus gravida quis blandit turpis. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing elit. Arcu dictum varius duis at. Et malesuada fames ac turpis egestas maecenas. Mi bibendum neque egestas congue quisque egestas. Sagittis orci a scelerisque purus semper. Leo vel orci porta non pulvinar neque. Tortor pretium viverra suspendisse potenti nullam ac.",
                            Name = "Lorem ipsum dolor",
                            Price = 1.00m,
                            ShortDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            TourId = 5
                        },
                        new
                        {
                            Id = 7,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum facilisis leo vel fringilla est ullamcorper. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Vitae ultricies leo integer malesuada. Dui id ornare arcu odio. Sit amet purus gravida quis blandit turpis. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing elit. Arcu dictum varius duis at. Et malesuada fames ac turpis egestas maecenas. Mi bibendum neque egestas congue quisque egestas. Sagittis orci a scelerisque purus semper. Leo vel orci porta non pulvinar neque. Tortor pretium viverra suspendisse potenti nullam ac.",
                            Name = "Lorem ipsum dolor",
                            Price = 4.00m,
                            ShortDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            TourId = 5
                        },
                        new
                        {
                            Id = 8,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum facilisis leo vel fringilla est ullamcorper. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Vitae ultricies leo integer malesuada. Dui id ornare arcu odio. Sit amet purus gravida quis blandit turpis. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing elit. Arcu dictum varius duis at. Et malesuada fames ac turpis egestas maecenas. Mi bibendum neque egestas congue quisque egestas. Sagittis orci a scelerisque purus semper. Leo vel orci porta non pulvinar neque. Tortor pretium viverra suspendisse potenti nullam ac.",
                            Name = "Lorem ipsum dolor",
                            Price = 3.50m,
                            ShortDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            TourId = 6
                        });
                });

            modelBuilder.Entity("CastleTours.Shared.Models.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CastleId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<int>("LoactionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CastleId");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CastleId = 1,
                            Email = "info@tytech.io",
                            FacilityId = 6,
                            LoactionId = 1,
                            Name = "Lorem ipsum",
                            Note = "Vitae ultricies leo integer malesuada. Dui id ornare arcu odio.",
                            Phone = "0456978722345",
                            Url = "https://tytech.io"
                        },
                        new
                        {
                            Id = 2,
                            CastleId = 2,
                            Email = "info@tytech.io",
                            FacilityId = 6,
                            LoactionId = 2,
                            Name = "Lorem ipsum",
                            Note = "Vitae ultricies leo integer malesuada. Dui id ornare arcu odio.",
                            Phone = "0456978722345",
                            Url = "https://tytech.io"
                        },
                        new
                        {
                            Id = 3,
                            CastleId = 3,
                            Email = "info@tytech.io",
                            FacilityId = 3,
                            LoactionId = 3,
                            Name = "Lorem ipsum",
                            Note = "Vitae ultricies leo integer malesuada. Dui id ornare arcu odio.",
                            Phone = "0456978722345",
                            Url = "https://tytech.io"
                        });
                });

            modelBuilder.Entity("CastleTours.Shared.Models.Castle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EnteranceFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EnteranceFeeSpecial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOpenToPublic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WikiUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LocationId");

                    b.ToTable("Castles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Condition = "Ruins",
                            Date = "13–14th century",
                            DateCreated = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4441),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pharetra viverra mattis. Maecenas at venenatis velit, nec sagittis felis. Proin ac ultricies justo, id vestibulum sem. Etiam sed diam quis dolor iaculis iaculis. Nullam augue ipsum, pharetra pharetra ex ac, molestie dignissim est. Duis in nulla ut odio scelerisque laoreet. Proin id suscipit diam. Vestibulum ullamcorper in ante suscipit iaculis.",
                            EnteranceFee = 12.00m,
                            EnteranceFeeSpecial = 0m,
                            ImgUrl = "https://upload.wikimedia.org/wikipedia/commons/d/d8/Beeston_Castle_Gate.jpg",
                            IsDeleted = false,
                            IsOpenToPublic = false,
                            IsPublic = false,
                            LocationId = 1,
                            Name = "Beeston Castle",
                            Summary = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pharetra viverra mattis.",
                            Type = "Enclosure castle",
                            WikiUrl = "https://en.wikipedia.org/wiki/Beeston_Castle"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Condition = "Fragment",
                            Date = "12th century",
                            DateCreated = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4448),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pharetra viverra mattis. Maecenas at venenatis velit, nec sagittis felis. Proin ac ultricies justo, id vestibulum sem. Etiam sed diam quis dolor iaculis iaculis. Nullam augue ipsum, pharetra pharetra ex ac, molestie dignissim est. Duis in nulla ut odio scelerisque laoreet. Proin id suscipit diam. Vestibulum ullamcorper in ante suscipit iaculis.",
                            EnteranceFee = 13.00m,
                            EnteranceFeeSpecial = 0m,
                            ImgUrl = "https://upload.wikimedia.org/wikipedia/commons/c/c0/Agricola_Tower%2C_Chester_Castle_-_geograph.org.uk_-_675807.jpg",
                            IsDeleted = false,
                            IsOpenToPublic = false,
                            IsPublic = false,
                            LocationId = 2,
                            Name = "Chester Castle",
                            Summary = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pharetra viverra mattis.",
                            Type = "Keep and bailey",
                            WikiUrl = "https://en.wikipedia.org/wiki/Chester_Castle"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Condition = "Intact",
                            Date = "1801–19th Century",
                            DateCreated = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4452),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pharetra viverra mattis. Maecenas at venenatis velit, nec sagittis felis. Proin ac ultricies justo, id vestibulum sem. Etiam sed diam quis dolor iaculis iaculis. Nullam augue ipsum, pharetra pharetra ex ac, molestie dignissim est. Duis in nulla ut odio scelerisque laoreet. Proin id suscipit diam. Vestibulum ullamcorper in ante suscipit iaculis.",
                            EnteranceFee = 0m,
                            EnteranceFeeSpecial = 0m,
                            ImgUrl = "https://upload.wikimedia.org/wikipedia/commons/5/51/Cholmondeley_-_Cholmondeley_Castle.jpg",
                            IsDeleted = false,
                            IsOpenToPublic = false,
                            IsPublic = false,
                            LocationId = 3,
                            Name = "Cholmondeley Castle",
                            Summary = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pharetra viverra mattis.",
                            Type = "Neo-romantic castle",
                            WikiUrl = "https://en.wikipedia.org/wiki/Cholmondeley_Castle"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Condition = "Substantially intact",
                            Date = "c. 1403",
                            DateCreated = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4455),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pharetra viverra mattis. Maecenas at venenatis velit, nec sagittis felis. Proin ac ultricies justo, id vestibulum sem. Etiam sed diam quis dolor iaculis iaculis. Nullam augue ipsum, pharetra pharetra ex ac, molestie dignissim est. Duis in nulla ut odio scelerisque laoreet. Proin id suscipit diam. Vestibulum ullamcorper in ante suscipit iaculis.",
                            EnteranceFee = 0m,
                            EnteranceFeeSpecial = 0m,
                            ImgUrl = "https://upload.wikimedia.org/wikipedia/commons/d/d1/%22Castle%22_in_the_park_%28cropped%29.jpg",
                            IsDeleted = false,
                            IsOpenToPublic = false,
                            IsPublic = false,
                            LocationId = 4,
                            Name = "Doddington Castle",
                            Summary = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pharetra viverra mattis.",
                            Type = "Tower house",
                            WikiUrl = "https://en.wikipedia.org/wiki/Delves_Hall"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Condition = "Fragmentary remains",
                            Date = "13th century",
                            DateCreated = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4459),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pharetra viverra mattis. Maecenas at venenatis velit, nec sagittis felis. Proin ac ultricies justo, id vestibulum sem. Etiam sed diam quis dolor iaculis iaculis. Nullam augue ipsum, pharetra pharetra ex ac, molestie dignissim est. Duis in nulla ut odio scelerisque laoreet. Proin id suscipit diam. Vestibulum ullamcorper in ante suscipit iaculis.",
                            EnteranceFee = 13.50m,
                            EnteranceFeeSpecial = 0m,
                            ImgUrl = "https://upload.wikimedia.org/wikipedia/commons/8/8a/Halton_Castle_-_geograph.org.uk_-_311820.jpg",
                            IsDeleted = false,
                            IsOpenToPublic = false,
                            IsPublic = false,
                            LocationId = 5,
                            Name = "Halton Castle",
                            Summary = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pharetra viverra mattis.",
                            Type = "Castle",
                            WikiUrl = "https://en.wikipedia.org/wiki/Halton_Castle"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Condition = "Intact",
                            Date = "1844–50",
                            DateCreated = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4463),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pharetra viverra mattis. Maecenas at venenatis velit, nec sagittis felis. Proin ac ultricies justo, id vestibulum sem. Etiam sed diam quis dolor iaculis iaculis. Nullam augue ipsum, pharetra pharetra ex ac, molestie dignissim est. Duis in nulla ut odio scelerisque laoreet. Proin id suscipit diam. Vestibulum ullamcorper in ante suscipit iaculis.",
                            EnteranceFee = 15.00m,
                            EnteranceFeeSpecial = 0m,
                            ImgUrl = "https://upload.wikimedia.org/wikipedia/commons/4/4b/Peckforton_Castle_1.jpg",
                            IsDeleted = false,
                            IsOpenToPublic = false,
                            IsPublic = false,
                            LocationId = 6,
                            Name = "Peckforton Castle",
                            Summary = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pharetra viverra mattis.",
                            Type = "Neo-romantic castle",
                            WikiUrl = "https://en.wikipedia.org/wiki/Peckforton_Castle"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Condition = "Intact",
                            Date = "11th - 21st Centuries",
                            DateCreated = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4467),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Site of a castle since the 12th century, Edinburgh Castle contains buildings of multiple periods and functions, including the royal palace, great hall, and 19th-century barracks.",
                            EnteranceFee = 18.00m,
                            EnteranceFeeSpecial = 0m,
                            ImgUrl = "https://upload.wikimedia.org/wikipedia/commons/4/4b/Peckforton_Castle_1.jpg",
                            IsDeleted = false,
                            IsOpenToPublic = false,
                            IsPublic = false,
                            LocationId = 7,
                            Name = "Edinburgh Castle",
                            Summary = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pharetra viverra mattis.",
                            Type = "Royal fortress",
                            WikiUrl = "https://en.wikipedia.org/wiki/Peckforton_Castle"
                        });
                });

            modelBuilder.Entity("CastleTours.Shared.Models.CastleComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CastleId")
                        .HasColumnType("int");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedApproved")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CastleId");

                    b.ToTable("CastleComments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Sit Amet",
                            CastleId = 1,
                            CommentText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum facilisis leo vel fringilla est ullamcorper. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus.",
                            CreatedDate = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4510),
                            Heading = "Lorem ipsum dolor sit amet",
                            IsPublic = false
                        },
                        new
                        {
                            Id = 2,
                            Author = "Sit Amet",
                            CastleId = 2,
                            CommentText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum facilisis leo vel fringilla est ullamcorper. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus.",
                            CreatedDate = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4515),
                            Heading = "Lorem ipsum dolor sit amet",
                            IsPublic = false
                        },
                        new
                        {
                            Id = 3,
                            Author = "Sit Amet",
                            CastleId = 2,
                            CommentText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum facilisis leo vel fringilla est ullamcorper. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus.",
                            CreatedDate = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4518),
                            Heading = "Lorem ipsum dolor sit amet",
                            IsPublic = false
                        },
                        new
                        {
                            Id = 4,
                            Author = "Sit Amet",
                            CastleId = 3,
                            CommentText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum facilisis leo vel fringilla est ullamcorper. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus.",
                            CreatedDate = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4521),
                            Heading = "Lorem ipsum dolor sit amet",
                            IsPublic = false
                        },
                        new
                        {
                            Id = 5,
                            Author = "Sit Amet",
                            CastleId = 4,
                            CommentText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum facilisis leo vel fringilla est ullamcorper. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus.",
                            CreatedDate = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4524),
                            Heading = "Lorem ipsum dolor sit amet",
                            IsPublic = false
                        },
                        new
                        {
                            Id = 6,
                            Author = "Sit Amet",
                            CastleId = 4,
                            CommentText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum facilisis leo vel fringilla est ullamcorper. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus.",
                            CreatedDate = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4527),
                            Heading = "Lorem ipsum dolor sit amet",
                            IsPublic = false
                        },
                        new
                        {
                            Id = 7,
                            Author = "Sit Amet",
                            CastleId = 4,
                            CommentText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum facilisis leo vel fringilla est ullamcorper. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus.",
                            CreatedDate = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4529),
                            Heading = "Lorem ipsum dolor sit amet",
                            IsPublic = false
                        },
                        new
                        {
                            Id = 8,
                            Author = "Sit Amet",
                            CastleId = 5,
                            CommentText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum facilisis leo vel fringilla est ullamcorper. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus.",
                            CreatedDate = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4533),
                            Heading = "Lorem ipsum dolor sit amet",
                            IsPublic = false
                        });
                });

            modelBuilder.Entity("CastleTours.Shared.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "puzzle-piece",
                            Name = "Family tours",
                            Url = "familytours"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "people",
                            Name = "12+ age tours",
                            Url = "12agetours"
                        });
                });

            modelBuilder.Entity("CastleTours.Shared.Models.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Facilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "oi oi-wifi",
                            Note = "Sit amet purus gravida quis blandit turpis.",
                            Type = "WiFi"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "oi oi-aperture",
                            Note = "Sit amet purus gravida quis blandit turpis.",
                            Type = "View Points"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "oi oi-audio",
                            Note = "Sit amet purus gravida quis blandit turpis.",
                            Type = "Hearing Aided"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "oi oi-basket",
                            Note = "Sit amet purus gravida quis blandit turpis.",
                            Type = "Gift Shop"
                        },
                        new
                        {
                            Id = 5,
                            Icon = "oi oi-british-pound",
                            Note = "Sit amet purus gravida quis blandit turpis.",
                            Type = "ATM"
                        },
                        new
                        {
                            Id = 6,
                            Icon = "oi oi-home",
                            Note = "Sit amet purus gravida quis blandit turpis.",
                            Type = "Resturant"
                        });
                });

            modelBuilder.Entity("CastleTours.Shared.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateFavorited")
                        .HasColumnType("datetime2");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateFavorited = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4174),
                            TourId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateFavorited = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4207),
                            TourId = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            DateFavorited = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4210),
                            TourId = 6,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            DateFavorited = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4213),
                            TourId = 9,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("CastleTours.Shared.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Coordinates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryIsoCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleMapsUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpenStreetMapUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = "Beeston",
                            Coordinates = "53.127700, -2.691300",
                            Country = "England",
                            CountryIsoCode = "gb",
                            GoogleMapsUrl = "https://www.google.com/maps?ll=53.1277,-2.6913&q=53.1277,-2.6913&hl=en&t=m&z=15",
                            OpenStreetMapUrl = "https://www.openstreetmap.org/?mlat=53.0572&mlon=-2.6932&zoom=15#map=15/53.0572/-2.6932",
                            Postcode = "CW6 9TX",
                            Region = "Cheshire",
                            Street = "Chapel Ln."
                        },
                        new
                        {
                            Id = 2,
                            Area = "Chester",
                            Coordinates = "53.185300, -2.892300",
                            Country = "England",
                            CountryIsoCode = "gb",
                            GoogleMapsUrl = "https://www.google.com/maps/place/53%C2%B011'07.1%22N+2%C2%B053'32.3%22W/@53.1853,-2.8923,15z/data=!4m5!3m4!1s0x0:0x174f34ec1d99a0dc!8m2!3d53.1853!4d-2.8923?hl=en",
                            OpenStreetMapUrl = "https://www.openstreetmap.org/?mlat=53.1853&mlon=-2.8923&zoom=15#map=15/53.1853/-2.8923",
                            Postcode = "CH1 2AN",
                            Region = "Cheshire",
                            Street = "Castle Dr."
                        },
                        new
                        {
                            Id = 3,
                            Area = "Malpas",
                            Coordinates = "53.057200, -2.693200",
                            Country = "England",
                            CountryIsoCode = "gb",
                            GoogleMapsUrl = "https://www.google.com/maps/place/53%C2%B003'25.9%22N+2%C2%B041'35.5%22W/@53.0572,-2.6932,15z/data=!4m5!3m4!1s0x0:0x3c0d89813010f4b1!8m2!3d53.0572!4d-2.6932?hl=en",
                            OpenStreetMapUrl = "https://www.openstreetmap.org/?mlat=53.0572&mlon=-2.6932&zoom=15#map=15/53.0572/-2.6932",
                            Postcode = "SY14 8AH",
                            Region = "Cheshire"
                        },
                        new
                        {
                            Id = 4,
                            Area = "Deddington",
                            Coordinates = "53.019700, -2.435600",
                            Country = "England",
                            CountryIsoCode = "gb",
                            GoogleMapsUrl = "https://www.google.com/maps/place/53%C2%B001'10.9%22N+2%C2%B026'08.2%22W/@53.0197,-2.4356,15z/data=!4m5!3m4!1s0x0:0x5d26ee0c75f80aa!8m2!3d53.0197!4d-2.4356?hl=en",
                            OpenStreetMapUrl = "https://www.openstreetmap.org/?mlat=53.0197&mlon=-2.4356&zoom=15#map=15/53.0197/-2.4356",
                            Postcode = "CW5 7NJ",
                            Region = "Oxford",
                            Street = "Castle Str."
                        },
                        new
                        {
                            Id = 5,
                            Area = "Halton",
                            Coordinates = "53.333100, -2.695700",
                            Country = "England",
                            CountryIsoCode = "gb",
                            GoogleMapsUrl = "https://www.google.com/maps/place/53%C2%B019'59.2%22N+2%C2%B041'44.5%22W/@53.3331,-2.6957,15z/data=!4m5!3m4!1s0x0:0xe8c1e4f7df5edf6!8m2!3d53.3331!4d-2.6957?hl=en",
                            OpenStreetMapUrl = "https://www.openstreetmap.org/?mlat=53.3331&mlon=-2.6957&zoom=15#map=15/53.3331/-2.6957",
                            Postcode = "WA7 2BE",
                            Region = "Chesire",
                            Street = "Castle Rd."
                        },
                        new
                        {
                            Id = 6,
                            Area = "Peckford",
                            Coordinates = "53.117500, -2.699000",
                            Country = "England",
                            CountryIsoCode = "gb",
                            GoogleMapsUrl = "https://www.google.com/maps/place/53%C2%B007'03.0%22N+2%C2%B041'56.4%22W/@53.1175,-2.699,15z/data=!4m5!3m4!1s0x0:0xf703599521b49084!8m2!3d53.1175!4d-2.699?hl=en",
                            OpenStreetMapUrl = "https://www.openstreetmap.org/?mlat=53.1175&mlon=-2.699&zoom=15#map=15/53.1175/-2.6990",
                            Postcode = "CW6 9TN",
                            Region = "Chesire",
                            Street = "Stone House Ln."
                        },
                        new
                        {
                            Id = 7,
                            Area = "Edinburgh",
                            Coordinates = "55.948611, -3.200833",
                            Country = "Scotland",
                            CountryIsoCode = "gb",
                            GoogleMapsUrl = "https://www.google.com/maps/place/55%C2%B056'55.0%22N+3%C2%B012'03.0%22W/@55.948611,-3.200833,15z/data=!4m5!3m4!1s0x0:0x5eaa0460843a6e07!8m2!3d55.948611!4d-3.200833?hl=en",
                            OpenStreetMapUrl = "https://www.openstreetmap.org/?mlat=55.948611&mlon=-3.200833&zoom=15#map=15/55.9486/-3.2008",
                            Postcode = "EH1 2YT",
                            Region = "",
                            Street = "Castlehill"
                        });
                });

            modelBuilder.Entity("CastleTours.Shared.Models.OperatingTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CastleId")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TourId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CastleId");

                    b.HasIndex("TourId");

                    b.ToTable("OperatingTimes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CastleId = 1,
                            Time = "27 Mar - 30 Sep (Daily): 10am - 5pm"
                        },
                        new
                        {
                            Id = 2,
                            CastleId = 1,
                            Time = "1 Oct - 31 Oct (Daily): 10am - 4pm"
                        },
                        new
                        {
                            Id = 3,
                            CastleId = 1,
                            Time = "1 Nov - 31 Mar (Sat - Sun): 10am - 4pm"
                        },
                        new
                        {
                            Id = 4,
                            CastleId = 1,
                            Time = "24 Dec - 26 Dec & 1 Jan: Cloased"
                        },
                        new
                        {
                            Id = 5,
                            CastleId = 2,
                            Time = "27 Mar - 30 Sep (Daily): 10am - 5pm"
                        },
                        new
                        {
                            Id = 6,
                            CastleId = 2,
                            Time = "1 Oct - 31 Oct (Daily): 10am - 4pm"
                        },
                        new
                        {
                            Id = 7,
                            CastleId = 2,
                            Time = "1 Nov - 31 Mar (Sat - Sun): 10am - 4pm"
                        },
                        new
                        {
                            Id = 8,
                            CastleId = 2,
                            Time = "24 Dec - 26 Dec & 1 Jan: Cloased"
                        },
                        new
                        {
                            Id = 9,
                            CastleId = 3,
                            Time = "27 Mar - 30 Sep (Daily): 10am - 5pm"
                        },
                        new
                        {
                            Id = 10,
                            CastleId = 3,
                            Time = "1 Oct - 31 Oct (Daily): 10am - 4pm"
                        },
                        new
                        {
                            Id = 11,
                            CastleId = 3,
                            Time = "1 Nov - 31 Mar (Sat - Sun): 10am - 4pm"
                        },
                        new
                        {
                            Id = 12,
                            CastleId = 3,
                            Time = "24 Dec - 26 Dec & 1 Jan: Cloased"
                        },
                        new
                        {
                            Id = 13,
                            CastleId = 4,
                            Time = "27 Mar - 30 Sep (Daily): 10am - 5pm"
                        },
                        new
                        {
                            Id = 14,
                            CastleId = 4,
                            Time = "1 Oct - 31 Oct (Daily): 10am - 4pm"
                        },
                        new
                        {
                            Id = 15,
                            CastleId = 4,
                            Time = "1 Nov - 31 Mar (Sat - Sun): 10am - 4pm"
                        },
                        new
                        {
                            Id = 16,
                            CastleId = 4,
                            Time = "24 Dec - 26 Dec & 1 Jan: Cloased"
                        },
                        new
                        {
                            Id = 17,
                            CastleId = 5,
                            Time = "27 Mar - 30 Sep (Daily): 10am - 5pm"
                        },
                        new
                        {
                            Id = 18,
                            CastleId = 5,
                            Time = "1 Oct - 31 Oct (Daily): 10am - 4pm"
                        },
                        new
                        {
                            Id = 19,
                            CastleId = 5,
                            Time = "1 Nov - 31 Mar (Sat - Sun): 10am - 4pm"
                        },
                        new
                        {
                            Id = 20,
                            CastleId = 5,
                            Time = "24 Dec - 26 Dec & 1 Jan: Cloased"
                        },
                        new
                        {
                            Id = 21,
                            CastleId = 6,
                            Time = "27 Mar - 30 Sep (Daily): 10am - 5pm"
                        },
                        new
                        {
                            Id = 22,
                            CastleId = 6,
                            Time = "1 Oct - 31 Oct (Daily): 10am - 4pm"
                        },
                        new
                        {
                            Id = 23,
                            CastleId = 6,
                            Time = "1 Nov - 31 Mar (Sat - Sun): 10am - 4pm"
                        },
                        new
                        {
                            Id = 24,
                            CastleId = 6,
                            Time = "24 Dec - 26 Dec & 1 Jan: Cloased"
                        },
                        new
                        {
                            Id = 25,
                            Time = "Saturdays 10am - 3pm",
                            TourId = 1
                        },
                        new
                        {
                            Id = 26,
                            Time = "Saturdays 10am - 3pm",
                            TourId = 2
                        },
                        new
                        {
                            Id = 27,
                            Time = "Saturdays 10am - 3pm",
                            TourId = 3
                        },
                        new
                        {
                            Id = 28,
                            Time = "Saturdays 10am - 3pm",
                            TourId = 4
                        },
                        new
                        {
                            Id = 29,
                            Time = "Saturdays 10am - 3pm",
                            TourId = 5
                        },
                        new
                        {
                            Id = 30,
                            Time = "Saturdays 10am - 3pm",
                            TourId = 6
                        },
                        new
                        {
                            Id = 31,
                            Time = "Saturdays 10am - 3pm",
                            TourId = 7
                        },
                        new
                        {
                            Id = 32,
                            Time = "Saturdays 10am - 3pm",
                            TourId = 8
                        },
                        new
                        {
                            Id = 33,
                            Time = "Mondays - Saturdays 9am - 4pm",
                            TourId = 9
                        },
                        new
                        {
                            Id = 34,
                            Time = "Sundays 9am - 3pm",
                            TourId = 9
                        });
                });

            modelBuilder.Entity("CastleTours.Shared.Models.Stats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("LastVisit")
                        .HasColumnType("datetime2");

                    b.Property<int>("Visits")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("CastleTours.Shared.Models.StoreTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("TicketCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StoreTransactions");
                });

            modelBuilder.Entity("CastleTours.Shared.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Blurb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CastleId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOperating")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SpecialPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CastleId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Tours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CastleId = 1,
                            CategoryId = 1,
                            DateCreated = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4340),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This tour is part of the National Heritage English History Tour. Its aimed at children 12 to 17 but adult are welcome to learn with us.",
                            ImgUrl = "https://www.getoutwiththekids.co.uk/wp-content/uploads/2019/10/Approaching-the-draw-bridge-castle-Day-Out.jpg",
                            IsDeleted = false,
                            IsFeatured = false,
                            IsOperating = true,
                            IsPublic = true,
                            Name = "Beeston Castle Kids Tour",
                            Price = 4.50m,
                            SpecialPrice = 3.50m
                        },
                        new
                        {
                            Id = 2,
                            CastleId = 1,
                            CategoryId = 2,
                            DateCreated = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4351),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This tour is part of the Wild Flowers Tour ",
                            ImgUrl = "https://www.getoutwiththekids.co.uk/wp-content/uploads/2019/10/Approaching-the-draw-bridge-castle-Day-Out.jpg",
                            IsDeleted = false,
                            IsFeatured = false,
                            IsOperating = true,
                            IsPublic = true,
                            Name = "Beeston Castle Garden Tour",
                            Price = 2m,
                            SpecialPrice = 0m
                        },
                        new
                        {
                            Id = 3,
                            CastleId = 2,
                            CategoryId = 2,
                            DateCreated = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4356),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This tour is part of the National Heritage English History Tour. Learn about the keep and bailey",
                            ImgUrl = "https://eu-assets.simpleview-europe.com/chester/imageresizer/?image=%2Fdmsimgs%2Fcastle_1980095267.png&action=ProductDetail",
                            IsDeleted = false,
                            IsFeatured = false,
                            IsOperating = true,
                            IsPublic = true,
                            Name = "Chester Castle",
                            Price = 9.00m,
                            SpecialPrice = 3.50m
                        },
                        new
                        {
                            Id = 4,
                            CastleId = 3,
                            CategoryId = 2,
                            DateCreated = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4360),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Come and join us for a romantic roam around one of Englands finest Neo-romantic castles.",
                            ImgUrl = "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/13/0e/df/8a/cholmondeley-castle.jpg?w=1200&h=1200&s=1",
                            IsDeleted = false,
                            IsFeatured = false,
                            IsOperating = true,
                            IsPublic = true,
                            Name = "Cholmondeley Tour",
                            Price = 10m,
                            SpecialPrice = 7.50m
                        },
                        new
                        {
                            Id = 5,
                            CastleId = 4,
                            CategoryId = 2,
                            DateCreated = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4364),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This tour is currently unavalible as the structure is currently deemed as unsafe.",
                            ImgUrl = "https://www.webbaviation.co.uk/aerial/_data/i/galleries/cheshire/doddington/Doddington_Castle_fb32098-me.jpg",
                            IsDeleted = false,
                            IsFeatured = false,
                            IsOperating = true,
                            IsPublic = true,
                            Name = "Doddington Tower Tour",
                            Price = 3m,
                            SpecialPrice = 0m
                        },
                        new
                        {
                            Id = 6,
                            CastleId = 4,
                            CategoryId = 1,
                            DateCreated = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4404),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This tour is currently unavalible as the structure is currently deemed as unsafe.",
                            ImgUrl = "https://www.webbaviation.co.uk/aerial/_data/i/galleries/cheshire/doddington/Doddington_Castle_fb32098-me.jpg",
                            IsDeleted = false,
                            IsFeatured = false,
                            IsOperating = true,
                            IsPublic = true,
                            Name = "Doddington Tower Kids Tour",
                            Price = 3m,
                            SpecialPrice = 0m
                        },
                        new
                        {
                            Id = 7,
                            CastleId = 5,
                            CategoryId = 2,
                            DateCreated = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4408),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This tour is part of the National Heritage English History Tour. Its aimed at children 12 to 17 but adult are welcome to learn with us.",
                            ImgUrl = "https://www.webbaviation.co.uk/aerial/galleries/cheshire/runcorn/Halton_Castle_Runcorn_jd28047.jpg",
                            IsDeleted = false,
                            IsFeatured = false,
                            IsOperating = true,
                            IsPublic = true,
                            Name = "Halton Castle",
                            Price = 4.50m,
                            SpecialPrice = 3.50m
                        },
                        new
                        {
                            Id = 8,
                            CastleId = 6,
                            CategoryId = 2,
                            DateCreated = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4411),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This tour is part of the National Heritage English History Tour. Its aimed at children 12 to 17 but adult are welcome to learn with us.",
                            ImgUrl = "https://cdn0.hitched.co.uk/vendor/3537/3_2/960/jpg/dji-0389-low-res_4_183537-163664362614439.jpeg",
                            IsDeleted = false,
                            IsFeatured = false,
                            IsOperating = true,
                            IsPublic = true,
                            Name = "Peckforton Castle Tour",
                            Price = 13m,
                            SpecialPrice = 10.50m
                        },
                        new
                        {
                            Id = 9,
                            Blurb = "Explore the most besieged castle in Eorupe!",
                            CastleId = 7,
                            CategoryId = 2,
                            DateCreated = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4415),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This tour is part of the National Heritage English History Tour. Its aimed at children 12 to 17 but adult are welcome to learn with us.",
                            ImgUrl = "https://th.bing.com/th/id/R.bb550545afd48d8ae77307363370a55d?rik=ZzKNsIDOcO3tPg&riu=http%3a%2f%2fwallup.net%2fwp-content%2fuploads%2f2016%2f01%2f207095-landscape-castle-Edinburgh-Scotland-UK.jpg&ehk=8eM1O612fOuUrOp1Aa9KhN03%2flt1%2fx6YcdNHavii6DA%3d&risl=&pid=ImgRaw&r=0",
                            IsDeleted = false,
                            IsFeatured = true,
                            IsOperating = true,
                            IsPublic = true,
                            Name = "The Besieged Tour",
                            Price = 32m,
                            SpecialPrice = 25m
                        });
                });

            modelBuilder.Entity("CastleTours.Shared.Models.TourComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedApproved")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.ToTable("TourComments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Sit Amet",
                            CommentText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum facilisis leo vel fringilla est ullamcorper. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus.",
                            CreatedDate = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4551),
                            Heading = "Lorem ipsum dolor sit amet",
                            IsPublic = false,
                            Rating = 3,
                            TourId = 1
                        },
                        new
                        {
                            Id = 2,
                            Author = "Sit Amet",
                            CommentText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum facilisis leo vel fringilla est ullamcorper. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus.",
                            CreatedDate = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4555),
                            Heading = "Lorem ipsum dolor sit amet",
                            IsPublic = false,
                            Rating = 4,
                            TourId = 1
                        },
                        new
                        {
                            Id = 3,
                            Author = "Sit Amet",
                            CommentText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum facilisis leo vel fringilla est ullamcorper. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus.",
                            CreatedDate = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4558),
                            Heading = "Lorem ipsum dolor sit amet",
                            IsPublic = false,
                            Rating = 5,
                            TourId = 2
                        },
                        new
                        {
                            Id = 4,
                            Author = "Sit Amet",
                            CommentText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum facilisis leo vel fringilla est ullamcorper. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus.",
                            CreatedDate = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4561),
                            Heading = "Lorem ipsum dolor sit amet",
                            IsPublic = false,
                            Rating = 2,
                            TourId = 3
                        },
                        new
                        {
                            Id = 5,
                            Author = "Sit Amet",
                            CommentText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum facilisis leo vel fringilla est ullamcorper. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus.",
                            CreatedDate = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4564),
                            Heading = "Lorem ipsum dolor sit amet",
                            IsPublic = false,
                            Rating = 5,
                            TourId = 3
                        },
                        new
                        {
                            Id = 6,
                            Author = "Sit Amet",
                            CommentText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum facilisis leo vel fringilla est ullamcorper. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus.",
                            CreatedDate = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4567),
                            Heading = "Lorem ipsum dolor sit amet",
                            IsPublic = false,
                            Rating = 4,
                            TourId = 3
                        },
                        new
                        {
                            Id = 7,
                            Author = "Sit Amet",
                            CommentText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum facilisis leo vel fringilla est ullamcorper. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus.",
                            CreatedDate = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4570),
                            Heading = "Lorem ipsum dolor sit amet",
                            IsPublic = false,
                            Rating = 4,
                            TourId = 4
                        },
                        new
                        {
                            Id = 8,
                            Author = "Sit Amet",
                            CommentText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum facilisis leo vel fringilla est ullamcorper. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus.",
                            CreatedDate = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4573),
                            Heading = "Lorem ipsum dolor sit amet",
                            IsPublic = false,
                            Rating = 3,
                            TourId = 4
                        },
                        new
                        {
                            Id = 9,
                            Author = "Sit Amet",
                            CommentText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum facilisis leo vel fringilla est ullamcorper. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus.",
                            CreatedDate = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4576),
                            Heading = "Lorem ipsum dolor sit amet",
                            IsPublic = false,
                            Rating = 5,
                            TourId = 5
                        },
                        new
                        {
                            Id = 10,
                            Author = "Sit Amet",
                            CommentText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum facilisis leo vel fringilla est ullamcorper. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus.",
                            CreatedDate = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4579),
                            Heading = "Lorem ipsum dolor sit amet",
                            IsPublic = false,
                            Rating = 4,
                            TourId = 5
                        },
                        new
                        {
                            Id = 11,
                            Author = "Sit Amet",
                            CommentText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum facilisis leo vel fringilla est ullamcorper. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus.",
                            CreatedDate = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4582),
                            Heading = "Lorem ipsum dolor sit amet",
                            IsPublic = false,
                            Rating = 3,
                            TourId = 6
                        },
                        new
                        {
                            Id = 12,
                            Author = "Sit Amet",
                            CommentText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum facilisis leo vel fringilla est ullamcorper. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus.",
                            CreatedDate = new DateTime(2022, 3, 3, 23, 6, 8, 516, DateTimeKind.Local).AddTicks(4585),
                            Heading = "Lorem ipsum dolor sit amet",
                            IsPublic = false,
                            Rating = 3,
                            TourId = 7
                        });
                });

            modelBuilder.Entity("CastleTours.Shared.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("ReadTsAndCs")
                        .HasColumnType("bit");

                    b.Property<bool>("RecieveNewsletters")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FacilityTour", b =>
                {
                    b.Property<int>("FacilitiesId")
                        .HasColumnType("int");

                    b.Property<int>("ToursId")
                        .HasColumnType("int");

                    b.HasKey("FacilitiesId", "ToursId");

                    b.HasIndex("ToursId");

                    b.ToTable("FacilityTour");

                    b.HasData(
                        new
                        {
                            FacilitiesId = 1,
                            ToursId = 1
                        },
                        new
                        {
                            FacilitiesId = 2,
                            ToursId = 1
                        },
                        new
                        {
                            FacilitiesId = 3,
                            ToursId = 1
                        },
                        new
                        {
                            FacilitiesId = 4,
                            ToursId = 2
                        },
                        new
                        {
                            FacilitiesId = 5,
                            ToursId = 2
                        },
                        new
                        {
                            FacilitiesId = 1,
                            ToursId = 2
                        },
                        new
                        {
                            FacilitiesId = 2,
                            ToursId = 3
                        },
                        new
                        {
                            FacilitiesId = 3,
                            ToursId = 3
                        },
                        new
                        {
                            FacilitiesId = 4,
                            ToursId = 4
                        },
                        new
                        {
                            FacilitiesId = 5,
                            ToursId = 4
                        },
                        new
                        {
                            FacilitiesId = 1,
                            ToursId = 4
                        },
                        new
                        {
                            FacilitiesId = 2,
                            ToursId = 4
                        },
                        new
                        {
                            FacilitiesId = 3,
                            ToursId = 5
                        },
                        new
                        {
                            FacilitiesId = 4,
                            ToursId = 6
                        });
                });

            modelBuilder.Entity("CastleFacility", b =>
                {
                    b.HasOne("CastleTours.Shared.Models.Castle", null)
                        .WithMany()
                        .HasForeignKey("CastlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CastleTours.Shared.Models.Facility", null)
                        .WithMany()
                        .HasForeignKey("FacilitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CastleTours.Shared.Models.Addon", b =>
                {
                    b.HasOne("CastleTours.Shared.Models.Tour", null)
                        .WithMany("Addons")
                        .HasForeignKey("TourId");
                });

            modelBuilder.Entity("CastleTours.Shared.Models.Amenity", b =>
                {
                    b.HasOne("CastleTours.Shared.Models.Castle", null)
                        .WithMany("Amenities")
                        .HasForeignKey("CastleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CastleTours.Shared.Models.Castle", b =>
                {
                    b.HasOne("CastleTours.Shared.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CastleTours.Shared.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("CastleTours.Shared.Models.CastleComment", b =>
                {
                    b.HasOne("CastleTours.Shared.Models.Castle", "Castle")
                        .WithMany("CastleComments")
                        .HasForeignKey("CastleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Castle");
                });

            modelBuilder.Entity("CastleTours.Shared.Models.Favorite", b =>
                {
                    b.HasOne("CastleTours.Shared.Models.User", null)
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CastleTours.Shared.Models.OperatingTime", b =>
                {
                    b.HasOne("CastleTours.Shared.Models.Castle", null)
                        .WithMany("OperatingTimes")
                        .HasForeignKey("CastleId");

                    b.HasOne("CastleTours.Shared.Models.Tour", null)
                        .WithMany("OperatingTimes")
                        .HasForeignKey("TourId");
                });

            modelBuilder.Entity("CastleTours.Shared.Models.Tour", b =>
                {
                    b.HasOne("CastleTours.Shared.Models.Castle", "Castle")
                        .WithMany("Tours")
                        .HasForeignKey("CastleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CastleTours.Shared.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Castle");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CastleTours.Shared.Models.TourComment", b =>
                {
                    b.HasOne("CastleTours.Shared.Models.Tour", "Tour")
                        .WithMany("TourComments")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("FacilityTour", b =>
                {
                    b.HasOne("CastleTours.Shared.Models.Facility", null)
                        .WithMany()
                        .HasForeignKey("FacilitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CastleTours.Shared.Models.Tour", null)
                        .WithMany()
                        .HasForeignKey("ToursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CastleTours.Shared.Models.Castle", b =>
                {
                    b.Navigation("Amenities");

                    b.Navigation("CastleComments");

                    b.Navigation("OperatingTimes");

                    b.Navigation("Tours");
                });

            modelBuilder.Entity("CastleTours.Shared.Models.Tour", b =>
                {
                    b.Navigation("Addons");

                    b.Navigation("OperatingTimes");

                    b.Navigation("TourComments");
                });

            modelBuilder.Entity("CastleTours.Shared.Models.User", b =>
                {
                    b.Navigation("Favorites");
                });
#pragma warning restore 612, 618
        }
    }
}
